name: schatWeb
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: ruieliu <majianbo@abhwllm.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  http_multi_server: ^2.1.0
  http_server: ^0.9.8+1
  logging: ^0.11.3+2

dev_dependencies:
  pedantic: ^1.0.0
